name: PHP Runner

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Fetch
      run: git clone https://github.com/zigou23/bing-wallpaper wp
      
    - name: Run PHP
      run: cd wp && sudo apt update && sudo apt install php7.4 -y && php7.4 ./json/generate15day.php

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./*.json
